openapi: "3.0.3"

info:
  title: "StockGPT API"
  description: |-
    StockGPT API from Rails API.
  version: "1.0.0"

servers:
  - url: https://api.example.com/api/v1
    description: production
  - url: https://{environment}.api.example.com/api/v1
    variables:
      environment:
        default: dev
        enum:
          - dev
          - staging
    description: develop
  - url: "{protocol}://{host}:{port}/api/v1"
    description: local
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
      port:
        enum:
          - '443'
          - '8443'
        default: '443'

tags:
  - name: Item
    description: Access to item model.

paths:
  /items:
    post:
      tags:
      - "Item"
      summary: CreateItem
      operationId: createItem
      requestBody:
        $ref: '#/components/requestBodies/CreateItemRequestBody'
      responses:
        '200':
          description: 作成済み商品
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemModel'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
                
  
    get:
      tags:
      - "Item"
      summary: 商品一覧取得
      description: 商品一覧
      operationId: getItemList
      responses:
        '200':
          $ref: '#/components/responses/GetItemsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
  /items/{id}:
    parameters:
      - $ref: '#/components/parameters/ItemIdParameter'
    get:
      tags:
        - "Item"
      summary: GetItemById
      description: |-
        Get item by id.
      responses:
        '200':
          $ref: '#/components/responses/GetItemResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
    patch:
      tags:
        - "Item"
      summary: UpdateItemById
      description: |-
        Update item by id.
      parameters:
        - $ref: '#/components/parameters/ItemIdParameter'
      requestBody:
        $ref: '#/components/requestBodies/UpdateItemRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/UpdateItemResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictErrorResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  
    delete:
      tags:
        - "Item"
      summary: DeleteItemById
      description: |-
        Delete item by id.
      parameters:
        - $ref: '#/components/parameters/ItemIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/GetItemResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictErrorResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
  /items/{id}/edit:
    parameters:
      - $ref: '#/components/parameters/ItemIdParameter'
    get:
      tags:
        - "Item"
      summary: EditItemById
      parameters:
        - $ref: '#/components/parameters/ItemIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/GetItemResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
    
components:
  schemas:
  #-------------------------------
  # Item schema
  #-------------------------------  
    ItemDynamicProps:
      type: object
      properties:
        name:
          type: string
          format: int64
          description: category of product
          example: Egg
        criteria:
          type: integer
          format: int64
          description: item id
          example: 22
        updated_at:
          type: string
          format: int64
          description: updated datetime
          example: 2023-01-21T17:32:28Z
          
    
    ItemStaticProps:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: item id
          example: 2
        created_at:
          type: string
          format: int64
          description: created datetime
          example: 2023-01-21T17:32:28Z
          
    ItemStaticPropsTwo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: item id
          example: 2
        created_at:
          type: string
          format: int64
          description: created datetime
          example: 2023-01-21T17:32:28Z
          
    ItemModel:
      type: object
      description: Item
      allOf:
        - $ref: '#/components/schemas/ItemDynamicProps'
        - $ref: '#/components/schemas/ItemStaticProps'
        
    ItemModelTwo:
      type: object
      description: Item
      allOf:
        - $ref: '#/components/schemas/ItemDynamicProps'
        - $ref: '#/components/schemas/ItemStaticPropsTwo'
      properties:
        name:
          type: string
          format: int64
          description: category of product
          example: Miso
        criteria:
          type: integer
          format: int64
          description: item id
          example: 333
        updated_at:
          type: string
          format: int64
          description: updated datetime
          example: 2023-03-23T17:32:28Z
          
          
    ItemModels:
      type: object
      properties:
        items:
          type: array
          items:
            oneOf:
            - type: object
              $ref: '#/components/schemas/ItemModel'
            - type: object
              $ref: '#/components/schemas/ItemModelTwo'
              
    
    ErrorModel:
      description: Response Error Model.
      required:
        - code
        - message
      type: object
      properties:
        code:
          title: error code
          type: string
          example: 500
        message:
          title: error message
          type: string
          example: Internal Server Error.
                
  #-------------------------------
  # Reusable operation parameters
  #-------------------------------
  parameters:
    ItemIdParameter:
      name: id
      in: path
      description: Item id.
      required: true
      schema:
        type: integer
      example: 2
    
  #-------------------------------
  # Reusable request body
  #-------------------------------  
  requestBodies:
    CreateItemRequestBody:
      description: item data
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ItemModel'
            
    UpdateItemRequestBody:
      description: item data
      required: true
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ItemModel'
              - properties:
                  name:
                    type: string
                    format: int64
                    description: category of product
                    example: Beef
                  criteria:
                    type: integer
                    format: int64
                    description: item id
                    example: 4
                  updated_at:
                    type: string
                    format: int64
                    description: updated datetime
                    example: 2023-01-21T17:32:28Z
                      
    


  #-------------------------------
  # Reusable responses
  #-------------------------------
  responses:
    GetItemsResponse:
        description: Item lists
        content:
          application/json:
            schema:
              allOf:
              - required:
                - items
              - type: object
              - properties:
                  items:
                    type: array
                    items:
                      oneOf:
                      - type: object
                        $ref: '#/components/schemas/ItemModel'
                      - type: object
                        $ref: '#/components/schemas/ItemModelTwo'
    
    GetItemResponse:
      description: Got item.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ItemModel'
              
    UpdateItemResponse:
      description: Updated item.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ItemModel'
              - properties:
                  name:
                    type: string
                    format: int64
                    description: category of product
                    example: Beef
                  criteria:
                    type: integer
                    format: int64
                    description: item id
                    example: 4
                  updated_at:
                    type: string
                    format: int64
                    description: updated datetime
                    example: 2023-01-21T17:32:28Z

    
    BadRequestResponse:
      description: | 
        Bad Request.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 400
              message:
                example: Bad Request.
                
    UnauthorizedResponse:
      description: | 
        Unauthorized.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 401
              message:
                example: Unauthorized.
                
    ForbiddenResponse:
      description: | 
        Forbidden.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 403
              message:
                example: Forbidden.
                
    NotFoundResponse:
      description: | 
        Not Found.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 404
              message:
                example: Not Found.
                
    ConflictErrorResponse:
      description: | 
        Conflict.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 409
              message:
                example: Conflict.
    InternalServerErrorResponse:
      description: |-
        Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
          
          
          