openapi: "3.0.3"

info:
  title: "StockGPT API"
  description: |-
    StockGPT API from Rails API.
  version: "1.0.0"

servers:
  - url: https://api.example.com/api/v1
    description: production
  - url: https://{environment}.api.example.com/api/v1
    variables:
      environment:
        default: dev
        enum:
          - dev
          - staging
    description: develop
  - url: "{protocol}://{host}:{port}/api/v1"
    description: local
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
      port:
        enum:
          - '443'
          - '8443'
        default: '443'

tags:
  - name: Group
    description: Access to group model.

paths:
  /groups:
    post:
      tags:
      - "Group"
      summary: CreateGroup
      operationId: createGroup
      requestBody:
        $ref: '#/components/requestBodies/CreateGroupRequestBody'
      responses:
        '200':
          description: 作成済みグループ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupModel'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
                
  
    get:
      tags:
      - "Group"
      summary: グループ一覧取得
      description: グループ一覧
      operationId: getGroupList
      responses:
        '200':
          $ref: '#/components/responses/GetGroupsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
  /groups/{id}:
    parameters:
      - $ref: '#/components/parameters/GroupIdParameter'
    get:
      tags:
        - "Group"
      summary: GetGroupById
      description: |-
        Get group by id.
      responses:
        '200':
          $ref: '#/components/responses/GetGroupResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
    patch:
      tags:
        - "Group"
      summary: UpdateGroupById
      description: |-
        Update group by id.
      parameters:
        - $ref: '#/components/parameters/GroupIdParameter'
      requestBody:
        $ref: '#/components/requestBodies/UpdateGroupRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/UpdateGroupResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictErrorResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  
    delete:
      tags:
        - "Group"
      summary: DeleteGroupById
      description: |-
        Delete group by id.
      parameters:
        - $ref: '#/components/parameters/GroupIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/GetGroupResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictErrorResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
  /groups/{id}/edit:
    parameters:
      - $ref: '#/components/parameters/GroupIdParameter'
    get:
      tags:
        - "Group"
      summary: EditGroupById
      parameters:
        - $ref: '#/components/parameters/GroupIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/GetGroupResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
    
components:
  schemas:
  #-------------------------------
  # Group schema
  #-------------------------------  
    GroupDynamicProps:
      type: object
      allOf:
        - $ref: '#/components/schemas/UpdateTimestamp'
      properties:
        name:
          type: string
          format: int64
          description: name
          example: groupname
    
    GroupStaticProps:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateTimestamp'
      properties:
        id:
          type: integer
          format: int64
          description: group id
          example: 2
        
    GroupStaticPropsTwo:
      type: object
      allOf:
        - $ref: '#/components/schemas/SecondCreateTimestamp'
      properties:
        id:
          type: integer
          format: int64
          description: group id
          example: 3
          
    GroupModel:
      type: object
      description: Group
      allOf:
        - $ref: '#/components/schemas/GroupDynamicProps'
        - $ref: '#/components/schemas/GroupStaticProps'
        
    GroupModelTwo:
      type: object
      description: Group
      allOf:
        - $ref: '#/components/schemas/GroupDynamicProps'
        - $ref: '#/components/schemas/GroupStaticPropsTwo'
        - $ref: '#/components/schemas/SecondUpdateTimestamp'
      properties:
        name:
          type: string
          format: int64
          description: name
          example: testnametwo

              
    
    ErrorModel:
      description: Response Error Model.
      required:
        - code
        - message
      type: object
      properties:
        code:
          title: error code
          type: string
          example: 500
        message:
          title: error message
          type: string
          example: Internal Server Error.
                
  #-------------------------------
  # Reusable operation parameters
  #-------------------------------
  parameters:
    GroupIdParameter:
      name: id
      in: path
      description: Group id.
      required: true
      schema:
        type: integer
      example: 2
    
  #-------------------------------
  # Reusable request body
  #-------------------------------  
  requestBodies:
    CreateGroupRequestBody:
      description: group data
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GroupModel'
            
    UpdateGroupRequestBody:
      description: group data
      required: true
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/GroupDynamicProps'
              - $ref: '#/components/schemas/EditUpdateTimestamp'
              - properties:
                  name:
                    type: string
                    format: int64
                    description: name
                    example: edited testnametwo
                  
            
    


  #-------------------------------
  # Reusable responses
  #-------------------------------
  responses:
    GetGroupsResponse:
        description: Group lists
        content:
          application/json:
            schema:
              allOf:
              - required:
                - groups
              - type: object
              - properties:
                  groups:
                    type: array
                    items:
                      oneOf:
                      - type: object
                        $ref: '#/components/schemas/GroupModel'
                      - type: object
                        $ref: '#/components/schemas/GroupModelTwo'
    
    GetGroupResponse:
      description: Got group.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/GroupModel'
              
    UpdateGroupResponse:
      description: Updated group.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/GroupModel'
              - properties:
                  name:
                    type: string
                    format: int64
                    description: name
                    example: testnametwo
                  nickname:
                    type: string
                    format: int64
                    description: nickname
                    example: test nicky
                  roommante_number:
                    type: integer
                    format: int64
                    description: roommante number
                    example: 3
                  prefecture:
                    type: string
                    format: int64
                    description: prefecture
                    example: 沖縄県

    
    BadRequestResponse:
      description: | 
        Bad Request.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 400
              message:
                example: Bad Request.
                
    UnauthorizedResponse:
      description: | 
        Unauthorized.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 401
              message:
                example: Unauthorized.
                
    ForbiddenResponse:
      description: | 
        Forbidden.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 403
              message:
                example: Forbidden.
                
    NotFoundResponse:
      description: | 
        Not Found.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 404
              message:
                example: Not Found.
                
    ConflictErrorResponse:
      description: | 
        Conflict.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 409
              message:
                example: Conflict.
    InternalServerErrorResponse:
      description: |-
        Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'