openapi: "3.0.3"

info:
  title: "StockGPT API"
  description: |-
    StockGPT API from Rails API.
  version: "1.0.0"

servers:
  - url: https://api.example.com/api/v1
    description: production
  - url: https://{environment}.api.example.com/api/v1
    variables:
      environment:
        default: dev
        enum:
          - dev
          - staging
    description: develop
  - url: "{protocol}://{host}:{port}/api/v1"
    description: local
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
      port:
        enum:
          - '443'
          - '8443'
        default: '443'

tags:
  - name: Request
    description: Access to request model.

paths:
  /requests:
    post:
      tags:
      - "Request"
      summary: CreateRequest
      operationId: createRequest
      requestBody:
        $ref: '#/components/requestBodies/CreateRequestRequestBody'
      responses:
        '200':
          description: 作成済みリクエストー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestModel'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
                
  
    get:
      tags:
      - "Request"
      summary: リクエスト覧取得
      description: リクエストー一覧
      operationId: getRequestList
      responses:
        '200':
          $ref: '#/components/responses/GetRequestsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
  /requests/{id}:
    parameters:
      - $ref: '#/components/parameters/RequestIdParameter'
    get:
      tags:
        - "Request"
      summary: GetRequestById
      description: |-
        Get request by id.
      responses:
        '200':
          $ref: '#/components/responses/GetRequestResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
    patch:
      tags:
        - "Request"
      summary: UpdateRequestById
      description: |-
        Update request by id.
      parameters:
        - $ref: '#/components/parameters/RequestIdParameter'
      requestBody:
        $ref: '#/components/requestBodies/UpdateRequestRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/UpdateRequestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictErrorResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  
    delete:
      tags:
        - "Request"
      summary: DeleteRequestById
      description: |-
        Delete request by id.
      parameters:
        - $ref: '#/components/parameters/RequestIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/GetRequestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictErrorResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
  /requests/{id}/edit:
    parameters:
      - $ref: '#/components/parameters/RequestIdParameter'
    get:
      tags:
        - "Request"
      summary: EditRequestById
      parameters:
        - $ref: '#/components/parameters/RequestIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/GetRequestResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
    
components:
  schemas:
  #-------------------------------
  # Request schema
  #-------------------------------  
    RequestDynamicProps:
      type: object
      allOf:
        - $ref: '#/components/schemas/UpdateTimestamp'
      properties:
        request_type:
          type: string
          format: int64
          description: category of request
          example: category_requests
        request_name:
          type: string
          format: int64
          description: request name
          example: toilet
          
    
    RequestStaticProps:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateTimestamp'
      properties:
        id:
          type: integer
          format: int64
          description: request id
          example: 2
          
    RequestStaticPropsTwo:
      type: object
      allOf:
        - $ref: '#/components/schemas/SecondCreateTimestamp'
      properties:
        id:
          type: integer
          format: int64
          description: request id
          example: 3
          
    RequestRegisterFlagOption:
      type: object
      properties:
        register_flag:
          type: boolean
          example: false
          
    RequestModel:
      type: object
      description: Request
      allOf:
        - $ref: '#/components/schemas/RequestDynamicProps'
        - $ref: '#/components/schemas/RequestStaticProps'
        - $ref: '#/components/schemas/RequestRegisterFlagOption'
        
    RequestModelTwo:
      type: object
      description: Request
      allOf:
        - $ref: '#/components/schemas/RequestDynamicProps'
        - $ref: '#/components/schemas/RequestStaticPropsTwo'
        - $ref: '#/components/schemas/RequestRegisterFlagOption'
        - $ref: '#/components/schemas/SecondUpdateTimestamp'
      properties:
        request_type:
          type: string
          format: int64
          description: request type
          example: category_groceries
        request_name:
          type: string
          format: int64
          description: request name
          example: kitchen
        register_flag:
          type: boolean
          example: true
          
    RequestModels:
      type: object
      properties:
        requests:
          type: array
          items:
            oneOf:
            - type: object
              $ref: '#/components/schemas/RequestModel'
            - type: object
              $ref: '#/components/schemas/RequestModelTwo'
              
    
    ErrorModel:
      description: Response Error Model.
      required:
        - code
        - message
      type: object
      properties:
        code:
          title: error code
          type: string
          example: 500
        message:
          title: error message
          type: string
          example: Internal Server Error.
                
  #-------------------------------
  # Reusable operation parameters
  #-------------------------------
  parameters:
    RequestIdParameter:
      name: id
      in: path
      description: Request id.
      required: true
      schema:
        type: integer
      example: 2
    
  #-------------------------------
  # Reusable request body
  #-------------------------------  
  requestBodies:
    CreateRequestRequestBody:
      description: request data
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestModel'
            
    UpdateRequestRequestBody:
      description: request data
      required: true
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/RequestModel'
              - $ref: '#/components/schemas/EditUpdateTimestamp'
              - properties:
                  request_type:
                    type: string
                    format: int64
                    description: category of request
                    example: category_requests
                  request_name:
                    type: string
                    format: int64
                    description: request name
                    example: toilet edited
                      
    


  #-------------------------------
  # Reusable responses
  #-------------------------------
  responses:
    GetRequestsResponse:
        description: Request lists
        content:
          application/json:
            schema:
              allOf:
              - required:
                - requests
              - type: object
              - properties:
                  requests:
                    type: array
                    items:
                      oneOf:
                      - type: object
                        $ref: '#/components/schemas/RequestModel'
                      - type: object
                        $ref: '#/components/schemas/RequestModelTwo'
    
    GetRequestResponse:
      description: Got request.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/RequestModel'
              
    UpdateRequestResponse:
      description: Updated request.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/RequestModel'
              - $ref: '#/components/schemas/EditUpdateTimestamp'
              - properties:
                  request_type:
                    type: string
                    format: int64
                    description: category of request
                    example: category_requests
                  request_name:
                    type: string
                    format: int64
                    description: request name
                    example: toilet edited

    
    BadRequestResponse:
      description: | 
        Bad Request.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 400
              message:
                example: Bad Request.
                
    UnauthorizedResponse:
      description: | 
        Unauthorized.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 401
              message:
                example: Unauthorized.
                
    ForbiddenResponse:
      description: | 
        Forbidden.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 403
              message:
                example: Forbidden.
                
    NotFoundResponse:
      description: | 
        Not Found.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 404
              message:
                example: Not Found.
                
    ConflictErrorResponse:
      description: | 
        Conflict.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 409
              message:
                example: Conflict.
    InternalServerErrorResponse:
      description: |-
        Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
          
          
          