openapi: "3.0.3"

info:
  title: "StockGPT API"
  description: |-
    StockGPT API from Rails API.
  version: "1.0.0"

servers:
  - url: https://api.example.com/api/v1
    description: production
  - url: https://{environment}.api.example.com/api/v1
    variables:
      environment:
        default: dev
        enum:
          - dev
          - staging
    description: develop
  - url: "{protocol}://{host}:{port}/api/v1"
    description: local
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
      port:
        enum:
          - '443'
          - '8443'
        default: '443'

tags:
  - name: CategoryProduct
    description: Access to category_product model.

paths:
  /category_products:
    post:
      tags:
      - "CategoryProduct"
      summary: CreateCategoryProduct
      operationId: createCategoryProduct
      requestBody:
        $ref: '#/components/requestBodies/CreateCategoryProductRequestBody'
      responses:
        '200':
          description: 作成済み日用品カテゴリー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryProductModel'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
                
  
    get:
      tags:
      - "CategoryProduct"
      summary: 日用品カテゴリー一覧取得
      description: 日用品カテゴリー一覧
      operationId: getCategoryProductList
      responses:
        '200':
          $ref: '#/components/responses/GetCategoryProductsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
  /category_products/{id}:
    parameters:
      - $ref: '#/components/parameters/CategoryProductIdParameter'
    get:
      tags:
        - "CategoryProduct"
      summary: GetCategoryProductById
      description: |-
        Get category_product by id.
      responses:
        '200':
          $ref: '#/components/responses/GetCategoryProductResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
    patch:
      tags:
        - "CategoryProduct"
      summary: UpdateCategoryProductById
      description: |-
        Update category_product by id.
      parameters:
        - $ref: '#/components/parameters/CategoryProductIdParameter'
      requestBody:
        $ref: '#/components/requestBodies/UpdateCategoryProductRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/UpdateCategoryProductResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictErrorResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  
    delete:
      tags:
        - "CategoryProduct"
      summary: DeleteCategoryProductById
      description: |-
        Delete category_product by id.
      parameters:
        - $ref: '#/components/parameters/CategoryProductIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/GetCategoryProductResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictErrorResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
  /category_products/{id}/edit:
    parameters:
      - $ref: '#/components/parameters/CategoryProductIdParameter'
    get:
      tags:
        - "CategoryProduct"
      summary: EditCategoryProductById
      parameters:
        - $ref: '#/components/parameters/CategoryProductIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/GetCategoryProductResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
    
components:
  schemas:
  #-------------------------------
  # CategoryProduct schema
  #-------------------------------  
    CategoryProductDynamicProps:
      type: object
      properties:
        name:
          type: string
          format: int64
          description: name
          example: test category name
        updated_at:
          type: string
          format: int64
          description: updated datetime
          example: 2023-01-21T17:32:28Z
    
    CategoryProductStaticProps:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: category_product id
          example: 2
        created_at:
          type: string
          format: int64
          description: created datetime
          example: 2023-01-21T17:32:28Z
          
    CategoryProductStaticPropsTwo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: category_product id
          example: 3
        created_at:
          type: string
          format: int64
          description: created datetime
          example: 2023-01-39T22:32:22Z
          
    CategoryProductModel:
      type: object
      description: CategoryProduct
      allOf:
        - $ref: '#/components/schemas/CategoryProductDynamicProps'
        - $ref: '#/components/schemas/CategoryProductStaticProps'
        
    CategoryProductModelTwo:
      type: object
      description: CategoryProduct
      allOf:
        - $ref: '#/components/schemas/CategoryProductDynamicProps'
        - $ref: '#/components/schemas/CategoryProductStaticPropsTwo'
      properties:
        name:
          type: string
          format: int64
          description: name
          example: test category name two
        updated_at:
          type: string
          format: int64
          description: updated datetime
          example: 2023-01-28T17:32:28Z
          
    CategoryProductModels:
      type: object
      properties:
        category_products:
          type: array
          items:
            oneOf:
            - type: object
              $ref: '#/components/schemas/CategoryProductModel'
            - type: object
              $ref: '#/components/schemas/CategoryProductModelTwo'
              
    
    ErrorModel:
      description: Response Error Model.
      required:
        - code
        - message
      type: object
      properties:
        code:
          title: error code
          type: string
          example: 500
        message:
          title: error message
          type: string
          example: Internal Server Error.
                
  #-------------------------------
  # Reusable operation parameters
  #-------------------------------
  parameters:
    CategoryProductIdParameter:
      name: id
      in: path
      description: CategoryProduct id.
      required: true
      schema:
        type: integer
      example: 2
    
  #-------------------------------
  # Reusable request body
  #-------------------------------  
  requestBodies:
    CreateCategoryProductRequestBody:
      description: category_product data
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CategoryProductModel'
            
    UpdateCategoryProductRequestBody:
      description: category_product data
      required: true
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/CategoryProductDynamicProps'
              - properties:
                  name:
                    type: string
                    format: int64
                    description: name
                    example: test category name request
                  updated_at:
                    type: string
                    format: int64
                    description: updated datetime
                    example: 2023-03-21T17:32:28Z
            
    


  #-------------------------------
  # Reusable responses
  #-------------------------------
  responses:
    GetCategoryProductsResponse:
        description: CategoryProduct lists
        content:
          application/json:
            schema:
              allOf:
              - required:
                - category_products
              - type: object
              - properties:
                  category_products:
                    type: array
                    items:
                      oneOf:
                      - type: object
                        $ref: '#/components/schemas/CategoryProductModel'
                      - type: object
                        $ref: '#/components/schemas/CategoryProductModelTwo'
    
    GetCategoryProductResponse:
      description: Got category_product.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/CategoryProductModel'
              
    UpdateCategoryProductResponse:
      description: Updated category_product.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/CategoryProductModel'
              - properties:
                  name:
                    type: string
                    format: int64
                    description: name
                    example: test category name request
                  updated_at:
                    type: string
                    format: int64
                    description: updated datetime
                    example: 2023-03-21T17:32:28Z

    
    BadRequestResponse:
      description: | 
        Bad Request.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 400
              message:
                example: Bad Request.
                
    UnauthorizedResponse:
      description: | 
        Unauthorized.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 401
              message:
                example: Unauthorized.
                
    ForbiddenResponse:
      description: | 
        Forbidden.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 403
              message:
                example: Forbidden.
                
    NotFoundResponse:
      description: | 
        Not Found.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 404
              message:
                example: Not Found.
                
    ConflictErrorResponse:
      description: | 
        Conflict.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 409
              message:
                example: Conflict.
    InternalServerErrorResponse:
      description: |-
        Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
          
          
          