openapi: "3.0.3"

info:
  title: "StockGPT API"
  description: |-
    StockGPT API from Rails API.
  version: "1.0.0"

servers:
  - url: https://api.example.com/api/v1
    description: production
  - url: https://{environment}.api.example.com/api/v1
    variables:
      environment:
        default: dev
        enum:
          - dev
          - staging
    description: develop
  - url: "{protocol}://{host}:{port}/api/v1"
    description: local
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
      port:
        enum:
          - '443'
          - '8443'
        default: '443'

tags:
  - name: SubCategoryGrocery
    description: Access to category_product model.

paths:
  /sub_category_groceries:
    post:
      tags:
      - "SubCategoryGrocery"
      summary: CreateSubCategoryGrocery
      operationId: createSubCategoryGrocery
      requestBody:
        $ref: '#/components/requestBodies/CreateSubCategoryGroceryRequestBody'
      responses:
        '200':
          description: 作成済み食料品サブカテゴリー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubCategoryGroceryModel'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
                
  
    get:
      tags:
      - "SubCategoryGrocery"
      summary: 食料品サブカテゴリー一覧取得
      description: 食料品サブカテゴリー一覧
      operationId: getSubCategoryGroceryList
      responses:
        '200':
          $ref: '#/components/responses/GetSubCategoryGroceriesResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
  /sub_category_groceries/{id}:
    parameters:
      - $ref: '#/components/parameters/SubCategoryGroceryIdParameter'
    get:
      tags:
        - "SubCategoryGrocery"
      summary: GetSubCategoryGroceryById
      description: |-
        Get category_product by id.
      responses:
        '200':
          $ref: '#/components/responses/GetSubCategoryGroceryResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
    patch:
      tags:
        - "SubCategoryGrocery"
      summary: UpdateSubCategoryGroceryById
      description: |-
        Update category_product by id.
      parameters:
        - $ref: '#/components/parameters/SubCategoryGroceryIdParameter'
      requestBody:
        $ref: '#/components/requestBodies/UpdateSubCategoryGroceryRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/UpdateSubCategoryGroceryResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictErrorResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  
    delete:
      tags:
        - "SubCategoryGrocery"
      summary: DeleteSubCategoryGroceryById
      description: |-
        Delete category_product by id.
      parameters:
        - $ref: '#/components/parameters/SubCategoryGroceryIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/GetSubCategoryGroceryResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictErrorResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
          
  /sub_category_groceries/{id}/edit:
    parameters:
      - $ref: '#/components/parameters/SubCategoryGroceryIdParameter'
    get:
      tags:
        - "SubCategoryGrocery"
      summary: EditSubCategoryGroceryById
      parameters:
        - $ref: '#/components/parameters/SubCategoryGroceryIdParameter'
      responses:
        '200':
          $ref: '#/components/responses/GetSubCategoryGroceryResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
    
components:
  schemas:
  #-------------------------------
  # SubCategoryGrocery schema
  #-------------------------------  
    SubCategoryGroceryDynamicProps:
      type: object
      allOf:
        - $ref: '#/components/schemas/UpdateTimestamp'
      properties:
        name:
          type: string
          format: int64
          description: name
          example: test category name
        category_id:
          type: string
          format: int64
          description: name
          example: 2
    
    SubCategoryGroceryStaticProps:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateTimestamp'
      properties:
        id:
          type: integer
          format: int64
          description: category_product id
          example: 2
          
    SubCategoryGroceryStaticPropsTwo:
      type: object
      allOf:
        - $ref: '#/components/schemas/SecondCreateTimestamp'
      properties:
        id:
          type: integer
          format: int64
          description: category_product id
          example: 3
          
    SubCategoryGroceryModel:
      type: object
      description: SubCategoryGrocery
      allOf:
        - $ref: '#/components/schemas/SubCategoryGroceryDynamicProps'
        - $ref: '#/components/schemas/SubCategoryGroceryStaticProps'
        
    SubCategoryGroceryModelTwo:
      type: object
      description: SubCategoryGrocery
      allOf:
        - $ref: '#/components/schemas/SubCategoryGroceryDynamicProps'
        - $ref: '#/components/schemas/SubCategoryGroceryStaticPropsTwo'
        - $ref: '#/components/schemas/SecondUpdateTimestamp'
      properties:
        name:
          type: string
          format: int64
          description: name
          example: test category name
        category_id:
          type: string
          format: int64
          description: name
          example: 3
          
    SubCategoryGroceryModels:
      type: object
      properties:
        sub_category_groceries:
          type: array
          items:
            oneOf:
            - type: object
              $ref: '#/components/schemas/SubCategoryGroceryModel'
            - type: object
              $ref: '#/components/schemas/SubCategoryGroceryModelTwo'
              
    
    ErrorModel:
      description: Response Error Model.
      required:
        - code
        - message
      type: object
      properties:
        code:
          title: error code
          type: string
          example: 500
        message:
          title: error message
          type: string
          example: Internal Server Error.
                
  #-------------------------------
  # Reusable operation parameters
  #-------------------------------
  parameters:
    SubCategoryGroceryIdParameter:
      name: id
      in: path
      description: SubCategoryGrocery id.
      required: true
      schema:
        type: integer
      example: 2
    
  #-------------------------------
  # Reusable request body
  #-------------------------------  
  requestBodies:
    CreateSubCategoryGroceryRequestBody:
      description: category_product data
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SubCategoryGroceryModel'
            
    UpdateSubCategoryGroceryRequestBody:
      description: category_product data
      required: true
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/SubCategoryGroceryDynamicProps'
              - $ref: '#/components/schemas/EditUpdateTimestamp'
              - properties:
                  name:
                    type: string
                    format: int64
                    description: name
                    example: test sub category name request
                  category_id:
                    type: string
                    format: int64
                    description: category_id
                    example: 4
            
    


  #-------------------------------
  # Reusable responses
  #-------------------------------
  responses:
    GetSubCategoryGroceriesResponse:
        description: SubCategoryGrocery lists
        content:
          application/json:
            schema:
              allOf:
              - required:
                - sub_category_groceries
              - type: object
              - properties:
                  sub_category_groceries:
                    type: array
                    items:
                      oneOf:
                      - type: object
                        $ref: '#/components/schemas/SubCategoryGroceryModel'
                      - type: object
                        $ref: '#/components/schemas/SubCategoryGroceryModelTwo'
    
    GetSubCategoryGroceryResponse:
      description: Got category_product.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/SubCategoryGroceryModel'
              
    UpdateSubCategoryGroceryResponse:
      description: Updated category_product.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/SubCategoryGroceryModel'
              - $ref: '#/components/schemas/EditUpdateTimestamp'
              - properties:
                  name:
                    type: string
                    format: int64
                    description: name
                    example: test sub category name request
                  category_id:
                    type: string
                    format: int64
                    description: category_id
                    example: 4

    
    BadRequestResponse:
      description: | 
        Bad Request.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 400
              message:
                example: Bad Request.
                
    UnauthorizedResponse:
      description: | 
        Unauthorized.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 401
              message:
                example: Unauthorized.
                
    ForbiddenResponse:
      description: | 
        Forbidden.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 403
              message:
                example: Forbidden.
                
    NotFoundResponse:
      description: | 
        Not Found.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 404
              message:
                example: Not Found.
                
    ConflictErrorResponse:
      description: | 
        Conflict.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorModel'
            properties:
              code:
                example: 409
              message:
                example: Conflict.
    InternalServerErrorResponse:
      description: |-
        Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
          
          
          