=begin
StockGPT API

StockGPT API from Rails API.

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class GetGroupList200ResponseAllOf < ApplicationRecord

  serialize :groups, Array
end
