=begin
StockGPT API

StockGPT API from Rails API.

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class GetToBuyListList200Response < ApplicationRecord
  validates_presence_of :to_buy_lists

  serialize :to_buy_lists, Array
end
