=begin
StockGPT API

StockGPT API from Rails API.

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "cart_dynamic_props".pluralize.to_sym, id: false do |t|
      t.integer :criteria
      t.integer :price
      t.string :updated_at

      t.timestamps
    end

    create_table "cart_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :deleted_at

      t.timestamps
    end

    create_table "cart_model_two".pluralize.to_sym, id: false do |t|
      t.integer :criteria
      t.integer :price
      t.string :updated_at
      t.string :deleted_at

      t.timestamps
    end

    create_table "cart_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :group_id
      t.integer :item_id
      t.string :updated_at

      t.timestamps
    end

    create_table "cart_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :group_id
      t.integer :item_id
      t.string :updated_at

      t.timestamps
    end

    create_table "_carts__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :deleted_at

      t.timestamps
    end

    create_table "_carts__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :deleted_at
      t.integer :criteria
      t.integer :price

      t.timestamps
    end

    create_table "_carts__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.integer :criteria
      t.integer :price

      t.timestamps
    end

    create_table "_category_groceries__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_category_groceries__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :name

      t.timestamps
    end

    create_table "_category_groceries__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.string :name

      t.timestamps
    end

    create_table "category_grocery_dynamic_props".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :updated_at

      t.timestamps
    end

    create_table "category_grocery_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "category_grocery_model_two".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :updated_at

      t.timestamps
    end

    create_table "category_grocery_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "category_grocery_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "category_product_dynamic_props".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :updated_at

      t.timestamps
    end

    create_table "category_product_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "category_product_model_two".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :updated_at

      t.timestamps
    end

    create_table "category_product_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "category_product_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "_category_products__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_category_products__id__patch_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :name

      t.timestamps
    end

    create_table "_category_products__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :name

      t.timestamps
    end

    create_table "_category_products__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.string :name

      t.timestamps
    end

    create_table "create_timestamp".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "criteria_dynamic_props".pluralize.to_sym, id: false do |t|
      t.integer :group_id
      t.integer :item_id
      t.integer :criteria
      t.string :updated_at

      t.timestamps
    end

    create_table "criteria_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "criteria_model_two".pluralize.to_sym, id: false do |t|
      t.integer :group_id
      t.integer :item_id
      t.integer :criteria
      t.string :updated_at

      t.timestamps
    end

    create_table "criteria_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "criteria_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "_criterias__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_criterias__id__patch_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.integer :group_id
      t.integer :item_id
      t.integer :criteria

      t.timestamps
    end

    create_table "_criterias__id__patch_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.integer :group_id
      t.integer :item_id
      t.integer :criteria

      t.timestamps
    end

    create_table "_criterias__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.integer :group_id
      t.integer :item_id
      t.integer :criteria

      t.timestamps
    end

    create_table "_criterias__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.integer :group_id
      t.integer :item_id
      t.integer :criteria

      t.timestamps
    end

    create_table "edit_update_timestamp".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "error_model".pluralize.to_sym, id: false do |t|
      t.string :code
      t.string :message

      t.timestamps
    end

    create_table "favorite_dynamic_props".pluralize.to_sym, id: false do |t|
      t.integer :item_id
      t.string :updated_at

      t.timestamps
    end

    create_table "favorite_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "favorite_model_two".pluralize.to_sym, id: false do |t|
      t.integer :item_id
      t.string :updated_at

      t.timestamps
    end

    create_table "favorite_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :group_id
      t.string :updated_at

      t.timestamps
    end

    create_table "favorite_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :group_id
      t.string :updated_at

      t.timestamps
    end

    create_table "_favorites__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_favorites__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.integer :item_id

      t.timestamps
    end

    create_table "get_cart_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :carts

      t.timestamps
    end

    create_table "get_cart_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :carts

      t.timestamps
    end

    create_table "get_cart_list_200_response_all_of_carts_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :deleted_at

      t.timestamps
    end

    create_table "get_category_grocery_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :category_groceries

      t.timestamps
    end

    create_table "get_category_grocery_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :category_groceries

      t.timestamps
    end

    create_table "get_category_grocery_list_200_response_all_of_category_groceries_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_category_product_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :category_products

      t.timestamps
    end

    create_table "get_category_product_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :category_products

      t.timestamps
    end

    create_table "get_category_product_list_200_response_all_of_category_products_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_criteria_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :criterias

      t.timestamps
    end

    create_table "get_criteria_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :criterias

      t.timestamps
    end

    create_table "get_criteria_list_200_response_all_of_criterias_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_favorite_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :favorites

      t.timestamps
    end

    create_table "get_favorite_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :favorites

      t.timestamps
    end

    create_table "get_favorite_list_200_response_all_of_favorites_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_grocery_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :grocerys

      t.timestamps
    end

    create_table "get_grocery_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :grocerys

      t.timestamps
    end

    create_table "get_grocery_list_200_response_all_of_grocerys_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_group_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :groups

      t.timestamps
    end

    create_table "get_group_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :groups

      t.timestamps
    end

    create_table "get_group_list_200_response_all_of_groups_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_invitation_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :invitations

      t.timestamps
    end

    create_table "get_invitation_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :invitations

      t.timestamps
    end

    create_table "get_invitation_list_200_response_all_of_invitations_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_item_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :items

      t.timestamps
    end

    create_table "get_item_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :items

      t.timestamps
    end

    create_table "get_item_list_200_response_all_of_items_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_maker_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :makers

      t.timestamps
    end

    create_table "get_maker_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :makers

      t.timestamps
    end

    create_table "get_maker_list_200_response_all_of_makers_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_product_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :products

      t.timestamps
    end

    create_table "get_product_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :products

      t.timestamps
    end

    create_table "get_product_list_200_response_all_of_products_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.integer :maker_id
      t.string :picture

      t.timestamps
    end

    create_table "get_profile_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :profiles

      t.timestamps
    end

    create_table "get_profile_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :profiles

      t.timestamps
    end

    create_table "get_profile_list_200_response_all_of_profiles_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_request_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :requests

      t.timestamps
    end

    create_table "get_request_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :requests

      t.timestamps
    end

    create_table "get_request_list_200_response_all_of_requests_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.boolean :register_flag

      t.timestamps
    end

    create_table "get_shop_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :shops

      t.timestamps
    end

    create_table "get_shop_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :shops

      t.timestamps
    end

    create_table "get_shop_list_200_response_all_of_shops_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_stock_item_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :stock_items

      t.timestamps
    end

    create_table "get_stock_item_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :stock_items

      t.timestamps
    end

    create_table "get_stock_item_list_200_response_all_of_stock_items_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.integer :price
      t.integer :shop_id

      t.timestamps
    end

    create_table "get_sub_category_grocery_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :sub_category_groceries

      t.timestamps
    end

    create_table "get_sub_category_grocery_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :sub_category_groceries

      t.timestamps
    end

    create_table "get_sub_category_grocery_list_200_response_all_of_sub_category_groceries_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_sub_category_product_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :sub_category_products

      t.timestamps
    end

    create_table "get_sub_category_product_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :sub_category_products

      t.timestamps
    end

    create_table "get_sub_category_product_list_200_response_all_of_sub_category_products_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "get_to_buy_list_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :to_buy_lists

      t.timestamps
    end

    create_table "get_to_buy_list_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :to_buy_lists

      t.timestamps
    end

    create_table "get_to_buy_list_list_200_response_all_of_to_buy_lists_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.boolean :buy_flag

      t.timestamps
    end

    create_table "get_user_list_200_response".pluralize.to_sym, id: false do |t|
      t.string :users

      t.timestamps
    end

    create_table "get_user_list_200_response_all_of".pluralize.to_sym, id: false do |t|
      t.string :users

      t.timestamps
    end

    create_table "get_user_list_200_response_all_of_users_inner".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.boolean :admin
      t.boolean :business

      t.timestamps
    end

    create_table "get_user_list_401_response".pluralize.to_sym, id: false do |t|
      t.Object :code
      t.Object :message

      t.timestamps
    end

    create_table "get_user_list_403_response".pluralize.to_sym, id: false do |t|
      t.Object :code
      t.Object :message

      t.timestamps
    end

    create_table "_groceries__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_groceries__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.integer :item_id
      t.integer :subcategory_id
      t.integer :category_id

      t.timestamps
    end

    create_table "_groceries__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.integer :item_id
      t.integer :subcategory_id
      t.integer :category_id

      t.timestamps
    end

    create_table "grocery_dynamic_props".pluralize.to_sym, id: false do |t|
      t.integer :item_id
      t.integer :subcategory_id
      t.integer :category_id
      t.string :updated_at

      t.timestamps
    end

    create_table "grocery_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "grocery_model_two".pluralize.to_sym, id: false do |t|
      t.integer :item_id
      t.integer :subcategory_id
      t.integer :category_id
      t.string :updated_at

      t.timestamps
    end

    create_table "grocery_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "grocery_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "group_dynamic_props".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :updated_at

      t.timestamps
    end

    create_table "group_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "group_model_two".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :updated_at

      t.timestamps
    end

    create_table "group_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "group_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "_groups__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_groups__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :name

      t.timestamps
    end

    create_table "_groups__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.string :name

      t.timestamps
    end

    create_table "invitation_dynamic_props".pluralize.to_sym, id: false do |t|
      t.integer :user_id
      t.string :updated_at

      t.timestamps
    end

    create_table "invitation_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "invitation_model_two".pluralize.to_sym, id: false do |t|
      t.integer :user_id
      t.string :updated_at

      t.timestamps
    end

    create_table "invitation_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :group_id
      t.string :updated_at

      t.timestamps
    end

    create_table "invitation_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :group_id
      t.string :updated_at

      t.timestamps
    end

    create_table "_invitations__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_invitations__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.integer :user_id

      t.timestamps
    end

    create_table "_invitations__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.integer :user_id

      t.timestamps
    end

    create_table "item_dynamic_props".pluralize.to_sym, id: false do |t|
      t.string :name
      t.integer :criteria
      t.string :updated_at

      t.timestamps
    end

    create_table "item_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "item_model_two".pluralize.to_sym, id: false do |t|
      t.string :name
      t.integer :criteria
      t.string :updated_at

      t.timestamps
    end

    create_table "item_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "item_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "_items__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_items__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :name
      t.integer :criteria

      t.timestamps
    end

    create_table "_items__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.string :name
      t.integer :criteria

      t.timestamps
    end

    create_table "maker_dynamic_props".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :updated_at

      t.timestamps
    end

    create_table "maker_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "maker_model_two".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :updated_at

      t.timestamps
    end

    create_table "maker_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "maker_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "_makers__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_makers__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :name

      t.timestamps
    end

    create_table "_makers__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.string :name

      t.timestamps
    end

    create_table "product_dynamic_props".pluralize.to_sym, id: false do |t|
      t.integer :item_id
      t.integer :subcategory_id
      t.integer :category_id
      t.string :updated_at

      t.timestamps
    end

    create_table "product_maker_option".pluralize.to_sym, id: false do |t|
      t.integer :maker_id

      t.timestamps
    end

    create_table "product_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.integer :maker_id
      t.string :picture

      t.timestamps
    end

    create_table "product_model_two".pluralize.to_sym, id: false do |t|
      t.integer :item_id
      t.integer :subcategory_id
      t.integer :category_id
      t.string :updated_at
      t.integer :maker_id
      t.string :picture

      t.timestamps
    end

    create_table "product_picture_option".pluralize.to_sym, id: false do |t|
      t.string :picture

      t.timestamps
    end

    create_table "product_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "product_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "_products__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.integer :maker_id
      t.string :picture

      t.timestamps
    end

    create_table "_products__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.integer :maker_id
      t.string :picture
      t.integer :item_id
      t.integer :subcategory_id
      t.integer :category_id

      t.timestamps
    end

    create_table "_products__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.integer :item_id
      t.integer :subcategory_id
      t.integer :category_id

      t.timestamps
    end

    create_table "profile_dynamic_props".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :nickname
      t.integer :roommante_number
      t.string :prefecture
      t.string :updated_at

      t.timestamps
    end

    create_table "profile_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "profile_model_two".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :nickname
      t.integer :roommante_number
      t.string :prefecture
      t.string :updated_at

      t.timestamps
    end

    create_table "profile_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :user_id
      t.string :updated_at

      t.timestamps
    end

    create_table "profile_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :user_id
      t.string :updated_at

      t.timestamps
    end

    create_table "_profiles__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_profiles__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :name
      t.string :nickname
      t.integer :roommante_number
      t.string :prefecture

      t.timestamps
    end

    create_table "_profiles__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :nickname
      t.integer :roommante_number
      t.string :prefecture

      t.timestamps
    end

    create_table "request_buy_flag_option".pluralize.to_sym, id: false do |t|
      t.boolean :buy_flag

      t.timestamps
    end

    create_table "request_deleted_option".pluralize.to_sym, id: false do |t|
      t.string :deleted_at

      t.timestamps
    end

    create_table "request_dynamic_props".pluralize.to_sym, id: false do |t|
      t.string :request_type
      t.string :request_name
      t.string :updated_at

      t.timestamps
    end

    create_table "request_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.boolean :register_flag

      t.timestamps
    end

    create_table "request_model_two".pluralize.to_sym, id: false do |t|
      t.string :request_type
      t.string :request_name
      t.boolean :register_flag
      t.string :updated_at

      t.timestamps
    end

    create_table "request_register_flag_option".pluralize.to_sym, id: false do |t|
      t.boolean :register_flag

      t.timestamps
    end

    create_table "request_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "request_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "_requests__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.boolean :register_flag

      t.timestamps
    end

    create_table "_requests__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.boolean :register_flag
      t.string :request_type
      t.string :request_name

      t.timestamps
    end

    create_table "_requests__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.string :request_type
      t.string :request_name

      t.timestamps
    end

    create_table "second_create_timestamp".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "second_update_timestamp".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "shop_dynamic_props".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :prefecture
      t.string :updated_at

      t.timestamps
    end

    create_table "shop_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "shop_model_two".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :prefecture
      t.string :updated_at

      t.timestamps
    end

    create_table "shop_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "shop_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "_shops__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_shops__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :name
      t.string :prefecture

      t.timestamps
    end

    create_table "_shops__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :prefecture

      t.timestamps
    end

    create_table "stock_item_dynamic_props".pluralize.to_sym, id: false do |t|
      t.integer :criteria
      t.string :alarm_date
      t.integer :quantity
      t.string :updated_at

      t.timestamps
    end

    create_table "stock_item_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "stock_item_model_two".pluralize.to_sym, id: false do |t|
      t.integer :criteria
      t.string :alarm_date
      t.integer :quantity
      t.string :updated_at
      t.integer :price
      t.integer :shop_id

      t.timestamps
    end

    create_table "stock_item_price_option".pluralize.to_sym, id: false do |t|
      t.integer :price

      t.timestamps
    end

    create_table "stock_item_shop_option".pluralize.to_sym, id: false do |t|
      t.integer :shop_id

      t.timestamps
    end

    create_table "stock_item_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :group_id
      t.string :updated_at

      t.timestamps
    end

    create_table "stock_item_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :group_id
      t.string :updated_at

      t.timestamps
    end

    create_table "_stock_items__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_stock_items__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.integer :price
      t.integer :shop_id
      t.integer :criteria
      t.string :alarm_date
      t.integer :quantity

      t.timestamps
    end

    create_table "_stock_items__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.integer :criteria
      t.string :alarm_date
      t.integer :quantity

      t.timestamps
    end

    create_table "_sub_category_groceries__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_sub_category_groceries__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :name
      t.string :category_id

      t.timestamps
    end

    create_table "_sub_category_groceries__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :category_id

      t.timestamps
    end

    create_table "sub_category_grocery_dynamic_props".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :category_id
      t.string :updated_at

      t.timestamps
    end

    create_table "sub_category_grocery_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "sub_category_grocery_model_two".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :category_id
      t.string :updated_at

      t.timestamps
    end

    create_table "sub_category_grocery_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "sub_category_grocery_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "sub_category_product_dynamic_props".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :category_id
      t.string :updated_at

      t.timestamps
    end

    create_table "sub_category_product_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "sub_category_product_model_two".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :category_id
      t.string :updated_at

      t.timestamps
    end

    create_table "sub_category_product_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "sub_category_product_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :updated_at

      t.timestamps
    end

    create_table "_sub_category_products__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "_sub_category_products__id__patch_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :name
      t.string :category_id

      t.timestamps
    end

    create_table "_sub_category_products__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.string :name
      t.string :category_id

      t.timestamps
    end

    create_table "to_buy_list_dynamic_props".pluralize.to_sym, id: false do |t|
      t.integer :item_id
      t.string :deleted_at
      t.string :updated_at

      t.timestamps
    end

    create_table "to_buy_list_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.boolean :buy_flag

      t.timestamps
    end

    create_table "to_buy_list_model_two".pluralize.to_sym, id: false do |t|
      t.integer :item_id
      t.string :deleted_at
      t.boolean :buy_flag
      t.string :updated_at

      t.timestamps
    end

    create_table "to_buy_list_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :group_id
      t.string :updated_at

      t.timestamps
    end

    create_table "to_buy_list_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :group_id
      t.string :updated_at

      t.timestamps
    end

    create_table "_to_buy_lists__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.boolean :buy_flag

      t.timestamps
    end

    create_table "_to_buy_lists__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.boolean :buy_flag
      t.integer :item_id

      t.timestamps
    end

    create_table "_to_buy_lists__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.integer :item_id

      t.timestamps
    end

    create_table "update_timestamp".pluralize.to_sym, id: false do |t|
      t.string :updated_at

      t.timestamps
    end

    create_table "user_admin_option".pluralize.to_sym, id: false do |t|
      t.boolean :admin

      t.timestamps
    end

    create_table "user_business_option".pluralize.to_sym, id: false do |t|
      t.boolean :business

      t.timestamps
    end

    create_table "user_dynamic_props".pluralize.to_sym, id: false do |t|
      t.string :email
      t.string :encrypted_password
      t.string :updated_at

      t.timestamps
    end

    create_table "user_model".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.boolean :admin
      t.boolean :business

      t.timestamps
    end

    create_table "user_model_two".pluralize.to_sym, id: false do |t|
      t.string :email
      t.string :encrypted_password
      t.boolean :admin
      t.string :updated_at
      t.boolean :business

      t.timestamps
    end

    create_table "user_static_props".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :group_id
      t.string :updated_at

      t.timestamps
    end

    create_table "user_static_props_two".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :group_id
      t.string :updated_at

      t.timestamps
    end

    create_table "_users__id__delete_409_response".pluralize.to_sym, id: false do |t|
      t.Object :code
      t.Object :message

      t.timestamps
    end

    create_table "_users__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.boolean :admin
      t.boolean :business

      t.timestamps
    end

    create_table "_users__id__get_400_response".pluralize.to_sym, id: false do |t|
      t.Object :code
      t.Object :message

      t.timestamps
    end

    create_table "_users__id__get_404_response".pluralize.to_sym, id: false do |t|
      t.Object :code
      t.Object :message

      t.timestamps
    end

    create_table "_users__id__patch_request".pluralize.to_sym, id: false do |t|
      t.string :updated_at
      t.boolean :admin
      t.boolean :business
      t.string :email
      t.string :encrypted_password

      t.timestamps
    end

    create_table "_users__id__patch_request_all_of".pluralize.to_sym, id: false do |t|
      t.string :email
      t.string :encrypted_password

      t.timestamps
    end

  end
end
