=begin
StockGPT API

StockGPT API from Rails API.

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class CartController < ApplicationController

  def carts_id_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def carts_id_edit_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def carts_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def carts_id_patch
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def create_cart
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_cart_list
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
