=begin
StockGPT API

StockGPT API from Rails API.

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class CategoryGroceryController < ApplicationController

  def category_groceries_id_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def category_groceries_id_edit_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def category_groceries_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def category_groceries_id_patch
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def create_category_grocery
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_category_grocery_list
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
