=begin
StockGPT API

StockGPT API from Rails API.

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class InvitationController < ApplicationController

  def create_invitation
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_invitation_list
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitations_id_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitations_id_edit_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitations_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitations_id_patch
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
