=begin
StockGPT API

StockGPT API from Rails API.

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class ShopController < ApplicationController

  def create_shop
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_shop_list
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shops_id_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shops_id_edit_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shops_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shops_id_patch
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
