=begin
StockGPT API

StockGPT API from Rails API.

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class StockItemController < ApplicationController

  def create_stock_item
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_stock_item_list
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def stock_items_id_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def stock_items_id_edit_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def stock_items_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def stock_items_id_patch
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
